apiVersion: v1
data:
  config: |
   nonMasqueradeCIDRs:
    - 10.96.0.0/12
    - 172.16.0.0/12
    - 192.168.0.0/16
   masqLinkLocal: false
   masqLinkLocalIPv6: true
   resyncInterval: 60s
kind: ConfigMap
metadata:
  name: ip-masq-agent
  namespace: kube-system
